# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ttawna/CLionProjects/fillit

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ttawna/CLionProjects/fillit/cmake-build-debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ttawna/CLionProjects/fillit/cmake-build-debug/CMakeFiles /Users/ttawna/CLionProjects/fillit/cmake-build-debug/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/ttawna/CLionProjects/fillit/cmake-build-debug/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fillit

# Build rule for target.
fillit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fillit
.PHONY : fillit

# fast build rule for target.
fillit/fast:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/build
.PHONY : fillit/fast

create.o: create.c.o

.PHONY : create.o

# target to build an object file
create.c.o:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/create.c.o
.PHONY : create.c.o

create.i: create.c.i

.PHONY : create.i

# target to preprocess a source file
create.c.i:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/create.c.i
.PHONY : create.c.i

create.s: create.c.s

.PHONY : create.s

# target to generate assembly for a file
create.c.s:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/create.c.s
.PHONY : create.c.s

first_check.o: first_check.c.o

.PHONY : first_check.o

# target to build an object file
first_check.c.o:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/first_check.c.o
.PHONY : first_check.c.o

first_check.i: first_check.c.i

.PHONY : first_check.i

# target to preprocess a source file
first_check.c.i:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/first_check.c.i
.PHONY : first_check.c.i

first_check.s: first_check.c.s

.PHONY : first_check.s

# target to generate assembly for a file
first_check.c.s:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/first_check.c.s
.PHONY : first_check.c.s

libft/ft_bzero.o: libft/ft_bzero.c.o

.PHONY : libft/ft_bzero.o

# target to build an object file
libft/ft_bzero.c.o:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_bzero.c.o
.PHONY : libft/ft_bzero.c.o

libft/ft_bzero.i: libft/ft_bzero.c.i

.PHONY : libft/ft_bzero.i

# target to preprocess a source file
libft/ft_bzero.c.i:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_bzero.c.i
.PHONY : libft/ft_bzero.c.i

libft/ft_bzero.s: libft/ft_bzero.c.s

.PHONY : libft/ft_bzero.s

# target to generate assembly for a file
libft/ft_bzero.c.s:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_bzero.c.s
.PHONY : libft/ft_bzero.c.s

libft/ft_memalloc.o: libft/ft_memalloc.c.o

.PHONY : libft/ft_memalloc.o

# target to build an object file
libft/ft_memalloc.c.o:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_memalloc.c.o
.PHONY : libft/ft_memalloc.c.o

libft/ft_memalloc.i: libft/ft_memalloc.c.i

.PHONY : libft/ft_memalloc.i

# target to preprocess a source file
libft/ft_memalloc.c.i:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_memalloc.c.i
.PHONY : libft/ft_memalloc.c.i

libft/ft_memalloc.s: libft/ft_memalloc.c.s

.PHONY : libft/ft_memalloc.s

# target to generate assembly for a file
libft/ft_memalloc.c.s:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_memalloc.c.s
.PHONY : libft/ft_memalloc.c.s

libft/ft_memcpy.o: libft/ft_memcpy.c.o

.PHONY : libft/ft_memcpy.o

# target to build an object file
libft/ft_memcpy.c.o:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_memcpy.c.o
.PHONY : libft/ft_memcpy.c.o

libft/ft_memcpy.i: libft/ft_memcpy.c.i

.PHONY : libft/ft_memcpy.i

# target to preprocess a source file
libft/ft_memcpy.c.i:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_memcpy.c.i
.PHONY : libft/ft_memcpy.c.i

libft/ft_memcpy.s: libft/ft_memcpy.c.s

.PHONY : libft/ft_memcpy.s

# target to generate assembly for a file
libft/ft_memcpy.c.s:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_memcpy.c.s
.PHONY : libft/ft_memcpy.c.s

libft/ft_memdel.o: libft/ft_memdel.c.o

.PHONY : libft/ft_memdel.o

# target to build an object file
libft/ft_memdel.c.o:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_memdel.c.o
.PHONY : libft/ft_memdel.c.o

libft/ft_memdel.i: libft/ft_memdel.c.i

.PHONY : libft/ft_memdel.i

# target to preprocess a source file
libft/ft_memdel.c.i:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_memdel.c.i
.PHONY : libft/ft_memdel.c.i

libft/ft_memdel.s: libft/ft_memdel.c.s

.PHONY : libft/ft_memdel.s

# target to generate assembly for a file
libft/ft_memdel.c.s:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_memdel.c.s
.PHONY : libft/ft_memdel.c.s

libft/ft_putchar_fd.o: libft/ft_putchar_fd.c.o

.PHONY : libft/ft_putchar_fd.o

# target to build an object file
libft/ft_putchar_fd.c.o:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_putchar_fd.c.o
.PHONY : libft/ft_putchar_fd.c.o

libft/ft_putchar_fd.i: libft/ft_putchar_fd.c.i

.PHONY : libft/ft_putchar_fd.i

# target to preprocess a source file
libft/ft_putchar_fd.c.i:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_putchar_fd.c.i
.PHONY : libft/ft_putchar_fd.c.i

libft/ft_putchar_fd.s: libft/ft_putchar_fd.c.s

.PHONY : libft/ft_putchar_fd.s

# target to generate assembly for a file
libft/ft_putchar_fd.c.s:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_putchar_fd.c.s
.PHONY : libft/ft_putchar_fd.c.s

libft/ft_putendl.o: libft/ft_putendl.c.o

.PHONY : libft/ft_putendl.o

# target to build an object file
libft/ft_putendl.c.o:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_putendl.c.o
.PHONY : libft/ft_putendl.c.o

libft/ft_putendl.i: libft/ft_putendl.c.i

.PHONY : libft/ft_putendl.i

# target to preprocess a source file
libft/ft_putendl.c.i:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_putendl.c.i
.PHONY : libft/ft_putendl.c.i

libft/ft_putendl.s: libft/ft_putendl.c.s

.PHONY : libft/ft_putendl.s

# target to generate assembly for a file
libft/ft_putendl.c.s:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_putendl.c.s
.PHONY : libft/ft_putendl.c.s

libft/ft_putstr_fd.o: libft/ft_putstr_fd.c.o

.PHONY : libft/ft_putstr_fd.o

# target to build an object file
libft/ft_putstr_fd.c.o:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_putstr_fd.c.o
.PHONY : libft/ft_putstr_fd.c.o

libft/ft_putstr_fd.i: libft/ft_putstr_fd.c.i

.PHONY : libft/ft_putstr_fd.i

# target to preprocess a source file
libft/ft_putstr_fd.c.i:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_putstr_fd.c.i
.PHONY : libft/ft_putstr_fd.c.i

libft/ft_putstr_fd.s: libft/ft_putstr_fd.c.s

.PHONY : libft/ft_putstr_fd.s

# target to generate assembly for a file
libft/ft_putstr_fd.c.s:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_putstr_fd.c.s
.PHONY : libft/ft_putstr_fd.c.s

libft/ft_strdel.o: libft/ft_strdel.c.o

.PHONY : libft/ft_strdel.o

# target to build an object file
libft/ft_strdel.c.o:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_strdel.c.o
.PHONY : libft/ft_strdel.c.o

libft/ft_strdel.i: libft/ft_strdel.c.i

.PHONY : libft/ft_strdel.i

# target to preprocess a source file
libft/ft_strdel.c.i:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_strdel.c.i
.PHONY : libft/ft_strdel.c.i

libft/ft_strdel.s: libft/ft_strdel.c.s

.PHONY : libft/ft_strdel.s

# target to generate assembly for a file
libft/ft_strdel.c.s:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_strdel.c.s
.PHONY : libft/ft_strdel.c.s

libft/ft_strdup.o: libft/ft_strdup.c.o

.PHONY : libft/ft_strdup.o

# target to build an object file
libft/ft_strdup.c.o:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_strdup.c.o
.PHONY : libft/ft_strdup.c.o

libft/ft_strdup.i: libft/ft_strdup.c.i

.PHONY : libft/ft_strdup.i

# target to preprocess a source file
libft/ft_strdup.c.i:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_strdup.c.i
.PHONY : libft/ft_strdup.c.i

libft/ft_strdup.s: libft/ft_strdup.c.s

.PHONY : libft/ft_strdup.s

# target to generate assembly for a file
libft/ft_strdup.c.s:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_strdup.c.s
.PHONY : libft/ft_strdup.c.s

libft/ft_strlen.o: libft/ft_strlen.c.o

.PHONY : libft/ft_strlen.o

# target to build an object file
libft/ft_strlen.c.o:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_strlen.c.o
.PHONY : libft/ft_strlen.c.o

libft/ft_strlen.i: libft/ft_strlen.c.i

.PHONY : libft/ft_strlen.i

# target to preprocess a source file
libft/ft_strlen.c.i:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_strlen.c.i
.PHONY : libft/ft_strlen.c.i

libft/ft_strlen.s: libft/ft_strlen.c.s

.PHONY : libft/ft_strlen.s

# target to generate assembly for a file
libft/ft_strlen.c.s:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_strlen.c.s
.PHONY : libft/ft_strlen.c.s

libft/ft_strsub.o: libft/ft_strsub.c.o

.PHONY : libft/ft_strsub.o

# target to build an object file
libft/ft_strsub.c.o:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_strsub.c.o
.PHONY : libft/ft_strsub.c.o

libft/ft_strsub.i: libft/ft_strsub.c.i

.PHONY : libft/ft_strsub.i

# target to preprocess a source file
libft/ft_strsub.c.i:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_strsub.c.i
.PHONY : libft/ft_strsub.c.i

libft/ft_strsub.s: libft/ft_strsub.c.s

.PHONY : libft/ft_strsub.s

# target to generate assembly for a file
libft/ft_strsub.c.s:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_strsub.c.s
.PHONY : libft/ft_strsub.c.s

libft/ft_strsub_free.o: libft/ft_strsub_free.c.o

.PHONY : libft/ft_strsub_free.o

# target to build an object file
libft/ft_strsub_free.c.o:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_strsub_free.c.o
.PHONY : libft/ft_strsub_free.c.o

libft/ft_strsub_free.i: libft/ft_strsub_free.c.i

.PHONY : libft/ft_strsub_free.i

# target to preprocess a source file
libft/ft_strsub_free.c.i:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_strsub_free.c.i
.PHONY : libft/ft_strsub_free.c.i

libft/ft_strsub_free.s: libft/ft_strsub_free.c.s

.PHONY : libft/ft_strsub_free.s

# target to generate assembly for a file
libft/ft_strsub_free.c.s:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/libft/ft_strsub_free.c.s
.PHONY : libft/ft_strsub_free.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/main.c.s
.PHONY : main.c.s

part_of_Nina.o: part_of_Nina.c.o

.PHONY : part_of_Nina.o

# target to build an object file
part_of_Nina.c.o:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/part_of_Nina.c.o
.PHONY : part_of_Nina.c.o

part_of_Nina.i: part_of_Nina.c.i

.PHONY : part_of_Nina.i

# target to preprocess a source file
part_of_Nina.c.i:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/part_of_Nina.c.i
.PHONY : part_of_Nina.c.i

part_of_Nina.s: part_of_Nina.c.s

.PHONY : part_of_Nina.s

# target to generate assembly for a file
part_of_Nina.c.s:
	$(MAKE) -f CMakeFiles/fillit.dir/build.make CMakeFiles/fillit.dir/part_of_Nina.c.s
.PHONY : part_of_Nina.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... fillit"
	@echo "... create.o"
	@echo "... create.i"
	@echo "... create.s"
	@echo "... first_check.o"
	@echo "... first_check.i"
	@echo "... first_check.s"
	@echo "... libft/ft_bzero.o"
	@echo "... libft/ft_bzero.i"
	@echo "... libft/ft_bzero.s"
	@echo "... libft/ft_memalloc.o"
	@echo "... libft/ft_memalloc.i"
	@echo "... libft/ft_memalloc.s"
	@echo "... libft/ft_memcpy.o"
	@echo "... libft/ft_memcpy.i"
	@echo "... libft/ft_memcpy.s"
	@echo "... libft/ft_memdel.o"
	@echo "... libft/ft_memdel.i"
	@echo "... libft/ft_memdel.s"
	@echo "... libft/ft_putchar_fd.o"
	@echo "... libft/ft_putchar_fd.i"
	@echo "... libft/ft_putchar_fd.s"
	@echo "... libft/ft_putendl.o"
	@echo "... libft/ft_putendl.i"
	@echo "... libft/ft_putendl.s"
	@echo "... libft/ft_putstr_fd.o"
	@echo "... libft/ft_putstr_fd.i"
	@echo "... libft/ft_putstr_fd.s"
	@echo "... libft/ft_strdel.o"
	@echo "... libft/ft_strdel.i"
	@echo "... libft/ft_strdel.s"
	@echo "... libft/ft_strdup.o"
	@echo "... libft/ft_strdup.i"
	@echo "... libft/ft_strdup.s"
	@echo "... libft/ft_strlen.o"
	@echo "... libft/ft_strlen.i"
	@echo "... libft/ft_strlen.s"
	@echo "... libft/ft_strsub.o"
	@echo "... libft/ft_strsub.i"
	@echo "... libft/ft_strsub.s"
	@echo "... libft/ft_strsub_free.o"
	@echo "... libft/ft_strsub_free.i"
	@echo "... libft/ft_strsub_free.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... part_of_Nina.o"
	@echo "... part_of_Nina.i"
	@echo "... part_of_Nina.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

